commands:
  enabled: true
  prefix: '>'
  channels: ['1170309999352872970']
  overrides:
    - name: 'ban'
      roles: ['1170309932214653001']

    - name: 'remove-punishment'
      roles: ['1219273039565422623']

punishments:
  editors: '1170309932214653001'
  managers: ['1213399995638616114', '1219273039565422623']

  defaultWarnDuration: 2592000000 # 1 month
  defaultMuteDuration: 21600000 # 6 hours

  additionalInfo:
    warn: 'If you feel like this punishment is unjustified, you may appeal it by messaging an Admin or higher.'
    mute: "If you feel like this punishment is unjustified, you may appeal it by messaging an Admin or higher."
    kick: 'If you feel like this punishment is unjustified, you may appeal it by messaging an Admin or higher.'
    ban: 'If you feel like this punishment is unjustified, you may appeal it by messaging an Admin or higher.'

lock:
  channels: ['1220275649550487612', '1170309998165905488', '1170309999352872970', '1169979209356169226', '1170310001777184878', '1170314103399657512', '1170310002909642812', '1169978174965305374']
  overrides: 377960303168 # Will deny Send Messages, Send Messages In Threads, Create Public/Private Threads, Attach Files, Add Reactions, Connect (vc), Speak (vc), Video (vc)

tags:
  - name: '1'
    aliases: ['respect', 'toxic']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "💞  Respect everyone at all times."
          value: "Hate speech, toxicity and/or harassment is strictly prohibited."
          inline: false
  - name: '2'
    aliases: ['mature', 'maturity']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "Act mature when interacting in our community."
          value: "Use the community productively and do not engage in debates or arguments. Report it to our team instead."
          inline: false
  - name: '3'
    aliases: ['sfw', 'nsfw']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "🔞  No inappropriate contributions."
          value: "This is not the place for NSFW images, messages or profiles. The same goes for overly sexual/suggestive conversations as well as sending unrelated links as we cannot keep our community safe outside of our community."
          inline: false
  - name: 'mod'
    aliases: ['apply', 'staff']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "How do I apply for staff?"
          value: "To become a staff member, you must apply through our staff application. This form is available in <#1169978382008721518> when we require more staff, and you'll usually require around Level 10+ and 2 or less warnings to apply (but this may change)."
          inline: false
  - name: 'slowmode'
    aliases: ['slow', 'sm']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "Why is slowmode so high?"
          value: "In order to effectively moderate chat, slowmode needs to be high so that moderators can view and punish users that break the rules. You can level up to gain access to chats with no slowmode!"
          inline: false
          
automod:
  filters:
    - name: 'No Swear Filter'
      enabled: false
      immuneRoles: ['1170309932214653001', '1219273039565422623', '1213399995638616114']
      immuneChannels: []
      punishment: 'Warn'
      duration: 86400000
      customInfo: 'We are a SFW server, please do not use swear words.'
      fallbackResponse: 'Please do not send prohibited words!'
      content: ['word1', 'word2', 'word3']

    - name: 'No Slur Filter'
      enabled: false
      immuneRoles: ['1170309932214653001', '1219273039565422623', '1213399995638616114']
      immuneChannels: []
      punishment: 'Ban'
      customInfo: 'We are a welcoming and inclusive community, as such we will not tolerate any slurs.'
      fallbackResponse: "Slurs aren't welcome here buddy. Goodbye."
      content: ['slur1', 'slur2', 'slur3']

  links:
    - name: 'All Links Filter'
      enabled: true
      immuneRoles: ['1170309932214653001', '1219273039565422623', '1213399995638616114']
      immuneChannels: []
      punishment: 'Warn'
      duration: 86400000
      customInfo: 'You are not allowed to send any links as they may contain malicious content.'
      fallbackResponse: 'Hi! Please do not send links, thanks!'
      whitelist: ['discord.com', 'discordapp.com', 'tenor.com'] # We whitelist the domain in the global filter but not in the tenor filter that gets triggered for users without any of the immune roles.

    - name: 'Tenor Links Filter'
      enabled: true
      immuneRoles: ['1170309946206847107', '1170309932214653001', '1219273039565422623', '1213399995638616114']
      immuneChannels: []
      punishment: 'Warn'
      duration: 86400000
      fallbackResponse: 'Hi! You cannot send tenor links yet as you are lacking an immune role to the tenor links filter!'
      whitelist: []

  mentions:
    - name: 'Owner Mention Filter'
      enabled: true
      immuneRoles: ['1170309932214653001', '1219273039565422623', '1213399995638616114']
      immuneChannels: []
      punishment: 'Warn'
      duration: 86400000
      fallbackResponse: 'Hi! You cannot ping the owners as they are busy and will not respond to your message.'
      list: ['851803979914805328']

    - name: 'Developer Mention Filter'
      enabled: true
      immuneRoles: ['1170309932214653001', '1219273039565422623', '1213399995638616114']
      immuneChannels: []
      punishment: 'Warn'
      duration: 86400000
      fallbackResponse: 'Hi! You cannot ping the developers as they are busy and will not respond to your message.'
      list: ['1005206283596611614']

  antiSpam:
    maxMentions:
      enabled: true
      immuneRoles: ['1170309932214653001', '1219273039565422623', '1213399995638616114']
      immuneChannels: []
      punishment: 'Warn'
      duration: 86400000
      limit: 8

    maxCharacters:
      enabled: true
      immuneRoles: ['1170309932214653001', '1219273039565422623', '1213399995638616114']
      immuneChannels: []
      punishment: 'Warn'
      duration: 86400000
      limit: 400

    maxAttachments:
      enabled: true
      immuneRoles: ['1170309932214653001', '1219273039565422623', '1213399995638616114']
      immuneChannels: ['1169979209356169226', '1169978174965305374']
      punishment: 'Warn'
      duration: 86400000
      limit: 6

logging:
  punishments:
    enabled: true
    channelId: '1218905992947957820'
  punishmentEdit:
    enabled: true
    channelId: '1218905992947957820'
  messages:
    enabled: true
    channelId: '1183711455007219732'
    excluded: ['channel-id', 'channel-id', 'channel-id']
  commands:
    enabled: false
    channelId: '1170309999352872970'
  mediaConversion:
    enabled: true 
    channelIds: '1219614615172808755'
    logChannelId: '1183711455007219732' 
